# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

syscfg.defs:
    ADXL345_SHELL_ITF_NUM:
        description: 'Shell interface number for the ADXL345'
        value: 0
    ADXL345_SHELL_ITF_TYPE:
        description: 'Shell interface type for the ADXL345'
        value: 1
    ADXL345_SHELL_CSPIN:
        description: 'CS pin for ADXL345'
        value : -1
    ADXL345_SHELL_ITF_ADDR:
        description: 'Slave address for ADXL345'
        value : 0x1D
    ADXL345_CLI:
        description: 'Enable shell support for the ADXL345'
        value: 0
    ADXL345_INT_ENABLE:
        description: 'Enable interrupt support, necessary for events'
        value: 1
    ADXL345_INT_CFG_ACTIVE:
        description: 'Set 0 for active-low, 1 for active-high'
        value: 1
    ADXL345_INT_CFG_OUTPUT:
        description: 'Set 0 for push-pull, 1 for open-drain'
        value: 1
    ADXL345_INT_PIN_HOST:
        description: 'Interrupt pin number on host device connected to INT on device'
        value: 1
    ADXL345_INT_PIN_DEVICE:
        description: 'Interrupt pin number 1 or 2 on accelerometer device'
        value: 1
    ADXL345_ITF_LOCK_TMO:
        description: 'ADXL345 interface lock timeout in milliseconds'
        value: 1000
    ADXL345_LOG_MODULE:
        description: 'Numeric module ID to use for ADXL345 log messages'
        value: 75
    ADXL345_I2C_RETRIES:
        description: >
            Number of retries to use for failed I2C communication.  A retry is
            used when the ADXL345 sends an unexpected NACK.
        value: 2
    ADXL345_ITF_ADDR:
        description: 'Slave address for ADXL345 (0x1D or 0x53)'
        value : 0x1D
