#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

bsp.arch: cortex_m4
bsp.compiler: compiler/arm-none-eabi-m4
bsp.linkerscript: "hw/bsp/frdm-k64f/MK64FN1M0xxx12_flash.ld"
bsp.linkerscript.BOOT_LOADER.OVERWRITE: "hw/bsp/frdm-k64f/boot-MK64FN1M0xxx12_flash.ld"
bsp.downloadscript: "hw/bsp/frdm-k64f/frdm-k64_download.sh"
bsp.debugscript: "hw/bsp/frdm-k64f/frdm-k64_debug.sh"
bsp.downloadscript.WINDOWS.OVERWRITE: "hw/bsp/frdm-k64f/frdm-k64_download.cmd"
bsp.debugscript.WINDOWS.OVERWRITE: "hw/bsp/frdm-k64f/frdm-k64_debug.cmd"

bsp.flash_map:
    areas:
        # System areas.
        FLASH_AREA_BOOTLOADER:
            device: 0
            offset: 0x00000000
            size: 24kB
        FLASH_AREA_IMAGE_SCRATCH:
            device: 0
            offset: 0x00006000
            size: 8kB
        FLASH_AREA_IMAGE_0:
            device: 0
            offset: 0x00008000
            size: 480kB
        FLASH_AREA_IMAGE_1:
            device: 0
            offset: 0x00080000
            size: 480kB

        # User areas
        FLASH_AREA_REBOOT_LOG:
            user_id: 0
            device: 0
            offset: 0x000F8000
            size: 16kB
        FLASH_AREA_NFFS:
            user_id: 1
            device: 0
            offset: 0x000FC000
            size: 16kB
