# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

syscfg.defs:
    MS5840_ITF_LOCK_TMO:
        description: 'MS5840 interface lock timeout in milliseconds'
        value: 1000
    MS5840_LOG_MODULE:
        description: 'Numeric module ID to use for MS5840 log messages'
        value: 170
    MS5840_I2C_RETRIES:
        description: >
            Number of retries to use for failed I2C communication.  A retry is
            used when the MS5840 sends an unexpected NACK.
        value: 2
    MS5840_I2C_TIMEOUT_TICKS:
        description: >
            Number of OS ticks to wait for each I2C transaction to complete.
        value: 3
