#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

pkg.name: hw/drivers/drv2605
pkg.description: i2c driver for the drv2605l in a Closed Loop LRA configuration based on SLOS854C REVISED SEPTEMBER 2014 datasheet
pkg.author: Jacob Rosenthal
pkg.homepage:
pkg.keywords:
    - drv2605
    - drv2605l
    - haptic
    - lra
    - i2c

pkg.deps:
    - "@apache-mynewt-core/kernel/os"
    - "@apache-mynewt-core/hw/hal"
    - "@apache-mynewt-core/hw/sensor"
    - "@apache-mynewt-core/hw/util/i2cn"
    - "@apache-mynewt-core/sys/log/modlog"

pkg.deps.DRV2605_CLI:
    - "@apache-mynewt-core/util/parse"
