#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

pkg.name: apps/testbench
pkg.type: app
pkg.description: target test suite for high-level mynewt OS functionality
pkg.author: "Apache Mynewt <dev@mynewt.apache.org>"
pkg.homepage: "http://mynewt.apache.org/"
pkg.keywords:

pkg.deps:
    - "@apache-mynewt-core/boot/bootutil"
    - "@apache-mynewt-core/boot/split_app"
    - "@apache-mynewt-core/encoding/json/test"
    - "@apache-mynewt-core/kernel/os"
    - "@apache-mynewt-core/kernel/os/test"
    - "@apache-mynewt-core/mgmt/imgmgr"
    - "@apache-mynewt-core/mgmt/oicmgr"
    - "@apache-mynewt-core/sys/config"
    - "@apache-mynewt-core/sys/console/full"
    - "@apache-mynewt-core/sys/flash_map"
    - "@apache-mynewt-core/sys/flash_map/test"
    - "@apache-mynewt-core/sys/id"
    - "@apache-mynewt-core/sys/log/full"
    - "@apache-mynewt-core/sys/log/modlog"
    - "@apache-mynewt-core/sys/stats/full"
    - "@apache-mynewt-core/test/crash_test"
    - "@apache-mynewt-core/test/runtest"
    - "@apache-mynewt-core/test/testutil"

pkg.deps.TESTBENCH_BLE:
    - "@apache-mynewt-nimble/nimble/controller"
    - "@apache-mynewt-nimble/nimble/host"
    - "@apache-mynewt-nimble/nimble/host/services/gap"
    - "@apache-mynewt-nimble/nimble/host/services/gatt"
    - "@apache-mynewt-nimble/nimble/host/store/ram"
    - "@apache-mynewt-nimble/nimble/transport/ram"

pkg.deps.CONFIG_NFFS:
    - "@apache-mynewt-core/fs/nffs"
    - "@apache-mynewt-core/fs/nffs/test"

pkg.deps.CONFIG_FCB:
    - "@apache-mynewt-core/fs/fcb"
    - "@apache-mynewt-core/fs/fcb/test"
