syscfg.vals:
    LOG_LEVEL: 0
    STATS_CLI: 1
    STATS_NAMES: 1

    BLE_SM_LEGACY: 0
    BLE_SM_SC: 1
    BLE_SM_BONDING: 1
    BLE_SM_MITM: 0
    BLE_SM_OOB_DATA_FLAG: 0
    BLE_SM_OUR_KEY_DIST: 7
    BLE_SM_THEIR_KEY_DIST: 7

    BLE_LL_CFG_FEAT_LE_ENCRYPTION: 1
    BLE_LL_CFG_FEAT_LL_PRIVACY: 1

    BLE_EDDYSTONE: 1

    BLE_LL_NUM_SCAN_DUP_ADVS: 32
    BLE_LL_NUM_SCAN_RSP_ADVS: 32
